import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Clone',
  description: 'Generated by create next app'
}

type Props = {
  children: ReactNode
  modal: ReactNode
}

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="en">
      <body className="bg-neutral-900 text-gray-100" suppressHydrationWarning>
        <>
          <div className="flex gap-6 py-2">
            <Link href="/">Home</Link>
            <Link href="/leaf">Leaf</Link>
            <Link href="/parallel-intercepting">Parallel+Intercepting Modal</Link>
            <Link href="/parallel">Parallel Modal</Link>
          </div>
          <hr className="mb-4" />
          {modal}
          {children}
        </>
      </body>
    </html>
  )
}
